import analyze_errors


def test_cik_of_extracts_leading_zero_padded_cik():
    assert analyze_errors.cik_of("0000012927_0000012927-20-000014") == 12927


def test_correct_prediction_classified_correct():
    lookup = {}
    record = {"doc_id": "0000012927_x", "field": "revenue",
              "predicted": 100.0, "true_value": 100.0, "unit": "USD"}
    assert analyze_errors.classify_record(record, lookup) == "correct"


def test_none_prediction_classified_parse_error_not_not_found():
    # Every record here was actually generated by the model, unlike the
    # source project's rules extractor which can abstain before running,
    # so a None prediction means unparseable output, not "never asked".
    lookup = {}
    record = {"doc_id": "0000012927_x", "field": "revenue",
              "predicted": None, "true_value": 100.0, "unit": "USD"}
    assert analyze_errors.classify_record(record, lookup) == "parse_error"


def test_off_by_power_of_ten_classified_scaling_error():
    lookup = {}
    record = {"doc_id": "0000012927_x", "field": "revenue",
              "predicted": 100_000.0, "true_value": 100_000_000.0, "unit": "USD"}
    assert analyze_errors.classify_record(record, lookup) == "scaling_error"


def test_matches_other_period_classified_wrong_period():
    lookup = {
        (12927, "revenue"): {"0000012927_other_year": 90.0}
    }
    record = {"doc_id": "0000012927_x", "field": "revenue",
              "predicted": 90.0, "true_value": 100.0, "unit": "USD"}
    assert analyze_errors.classify_record(record, lookup) == "wrong_period"


def test_unrelated_number_classified_wrong_row():
    lookup = {}
    record = {"doc_id": "0000012927_x", "field": "revenue",
              "predicted": 42.0, "true_value": 100.0, "unit": "USD"}
    assert analyze_errors.classify_record(record, lookup) == "wrong_row"


def test_other_period_lookup_excludes_the_record_own_doc_id():
    lookup = {
        (12927, "revenue"): {"0000012927_x": 100.0, "0000012927_other": 90.0}
    }
    record = {"doc_id": "0000012927_x", "field": "revenue",
              "predicted": 100.0, "true_value": 100.0, "unit": "USD"}
    # predicted equals its OWN doc's true_value too, but that's the
    # correct case already, checked before wrong_period is ever reached;
    # this guards that build_other_period_lookup-derived values passed in
    # here don't leak the record's own answer into "other" periods.
    assert analyze_errors.classify_record(record, lookup) == "correct"
