"""
Breaks each wrong prediction down by failure kind rather than reporting a
single accuracy percentage, reusing filing-extraction-benchmark's own
`classify()` (the exact function that project's own three methods are
compared with) so a category here means the same thing it means there:

  correct        within tolerance of the filed value
  scaling_error  the right figure, off by a power of ten (a scale-
                 conversion miss, exactly the failure src/data_prep.py's
                 [scale: ...] tagging targets)
  wrong_period   the right figure, but for a different fiscal year of the
                 same company and field
  wrong_row      a different number entirely, the model read past the
                 model's own instruction to convert scale, or picked an
                 unrelated row
  parse_error    the model's output had no number `parse_numeric` could
                 extract at all

`predicted is None` is always classified as parse_error, not not_found:
every example here was actually generated by the model (unlike the
source project's rules extractor, which can abstain before generating
anything), so a None prediction means the model produced text with no
extractable number, not that it was never asked.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

import pandas as pd

SOURCE_PROJECT = Path(__file__).resolve().parents[2] / "filing-extraction-benchmark"
sys.path.insert(0, str(SOURCE_PROJECT / "src"))
from filingbench.scoring import classify  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = ROOT / "results"


def cik_of(doc_id: str) -> int:
    return int(doc_id.split("_")[0])


def build_other_period_lookup() -> dict[tuple[int, str], dict[str, float]]:
    """Maps (cik, field) -> {doc_id: true_value} for every ground truth row.

    classify() wants, per prediction, the true values of the SAME field
    reported in the company's OTHER filings, to tell a wrong-period miss
    (grabbed last year's column) apart from an actually wrong row. Built
    from the source project's own ground_truth.csv, read only.
    """
    gt = pd.read_csv(SOURCE_PROJECT / "results" / "ground_truth.csv")
    lookup: dict[tuple[int, str], dict[str, float]] = {}
    for (cik, field), group in gt.groupby(["cik", "field"]):
        lookup[(cik, field)] = dict(zip(group["doc_id"], group["true_value"]))
    return lookup


def classify_record(record: dict, other_period_lookup: dict) -> str:
    doc_id, field = record["doc_id"], record["field"]
    others = other_period_lookup.get((cik_of(doc_id), field), {})
    other_values = [v for d, v in others.items() if d != doc_id]
    status = "unparseable_response" if record["predicted"] is None else "llm_answered"
    return classify(record["predicted"], status, record["true_value"], record["unit"], other_values)


def summarize(label: str) -> Counter:
    records = json.load(open(RESULTS_DIR / f"predictions_{label}.json"))
    lookup = build_other_period_lookup()
    counts = Counter(classify_record(r, lookup) for r in records)
    n = len(records)
    print(f"\n{label} (n={n}):")
    for kind in ["correct", "scaling_error", "wrong_period", "wrong_row", "parse_error", "not_found"]:
        if kind in counts:
            print(f"  {kind:15s} {counts[kind]:4d}  ({counts[kind] / n:.1%})")
    return counts


def wrong_row_rate_by(label: str, group_key: str) -> dict[str, tuple[int, int, float]]:
    """wrong_row count, group size, and rate for each distinct value of
    record[group_key] (e.g. "field" or "company"), sorted by rate
    descending. Answers whether the dominant failure mode is spread
    evenly or concentrated, a flat rate across fields/companies points
    at a model-capability ceiling; a concentrated one points at a
    specific, possibly fixable cause (one field's table layout, one
    company's formatting).
    """
    records = json.load(open(RESULTS_DIR / f"predictions_{label}.json"))
    lookup = build_other_period_lookup()
    kinds = {(r["doc_id"], r["field"]): classify_record(r, lookup) for r in records}

    totals: Counter = Counter()
    wrong_rows: Counter = Counter()
    for r in records:
        key = r[group_key]
        totals[key] += 1
        if kinds[(r["doc_id"], r["field"])] == "wrong_row":
            wrong_rows[key] += 1

    result = {
        key: (wrong_rows[key], totals[key], wrong_rows[key] / totals[key])
        for key in totals
    }
    print(f"\n{label}: wrong_row rate by {group_key} (n={len(records)} total)")
    for key, (n_wrong, n_total, rate) in sorted(result.items(), key=lambda kv: -kv[1][2]):
        print(f"  {key:45s} {n_wrong:4d}/{n_total:<4d}  ({rate:.1%})")
    return result


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("labels", nargs="*", default=["zeroshot_base"])
    parser.add_argument("--by", choices=["field", "company"], default=None,
                         help="break the wrong_row rate down by this key instead of the overall summary")
    args = parser.parse_args()

    for label in args.labels:
        if args.by:
            wrong_row_rate_by(label, args.by)
        else:
            summarize(label)
